---
title: 'R-Spatial : présentation des données utilisées'
author: "Cyril Bernard (CEFE-CNRS)"
date: "30 janvier 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## sp: COURS
- 7 points dans Montpellier
- un fichier de ligne de tramway ?
- 

## sp: EXERCICES

over:
dist matrix:

## MMM liens


# DONNEES

- https://data.montpellier3m.fr/dataset/contours-des-communes-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/stations-velomagg-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/arrets-de-bus-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/arrets-de-tramway-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/reseau-de-tramway-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/population-2008-carroyage-insee-sur-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/reseau-de-bus-lignes-suburbaines-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/reseau-de-bus-lignes-urbaines-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/parcs-et-jardins-de-montpellier-mediterranee-metropole
- http://data.montpellier3m.fr/dataset/parcs-et-jardins-surface-de-montpellier
- https://data.montpellier3m.fr/dataset/arbres-remarquables-de-montpellier
- https://data.montpellier3m.fr/dataset/iris
- https://data.montpellier3m.fr/dataset/restaurants-bars-et-cafes-de-montpellier-mediterranee-metropole
- https://data.montpellier3m.fr/dataset/synth%C3%A8se-des-voies-en-mode-doux-de-montpellier
- http://data.montpellier3m.fr/dataset/resultats-des-elections-montpellier
- http://data.montpellier3m.fr/dataset/bureaux-de-vote-de-montpellier

- http://data.montpellier3m.fr/sites/default/files/ressources/VilleMTP_MTP_Elections.csv
- http://data.montpellier3m.fr/sites/default/files/ressources/VilleMTP_MTP_BureauxVote.geojson

## Télécharger les données

```{r}
setwd("data")
url1 <- "https://data.montpellier3m.fr/sites/default/files/ressources/MMM_MMM_Limites.zip"
url2 <- "https://data.montpellier3m.fr/sites/default/files/ressources/MMM_MMM_ArretsBusUrb.zip"
url3 <- "https://data.montpellier3m.fr/sites/default/files/ressources/MMM_MMM_ArretsTram.zip"
download.file(URL,"Rmeeting.zip")
unzip("Rmeeting.zip")
```

