---
title: "seance2_exercices"
author: "Cyril Bernard (CEFE-CNRS)"
date: "17 juillet 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lire les valeurs d'un raster
```{r}
v <- rvide[]
rvide[] <- runif(360*180,0,10)
rvide[1]
xyFromCell(rvide,1)
mtp_coords <- matrix(c(3.8,43.6),ncol=2)
ncell<-cellFromXY(rvide,mtp_coords)
rowColFromCell(rvide,ncell)
```

## 'RATifier' un raster avec des valeurs catégorielles
La 'RAT' (_Raster Attribute Table_) permet d'associer des libellés aux différentes catégories codées sous forme d'entier dans le raster.
```{r Créer RAT}
rast_clc_categ <- as.factor(rast_clc80_niv2)
# ou bien, pour la fréquence des catégories :
rast_clc_categ <- ratify(rast_clc80_niv2, count=T)
df_clc_categ <- levels(rast_clc_categ)[[1]]
df_clc_categ <- inner_join(df_clc_categ, df_nom2, by="ID")
levels(rast_clc_categ)[[1]] <- df_clc_categ
```


```{r tmap et raster}
library(tmap)
tm_shape(rast_clc_categ) +
  tm_raster(col="LIB_FR", style="cat")
tm_shape(rast_clc_categ) +
  tm_raster("PAL", style="cat")
tm_shape(rast_clc_categ) +
  tm_raster("CODE", style="cat", palette = df_clc_categ$PAL)
```

